//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rnd.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rnd.Common.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention cannot be blank..
        /// </summary>
        public static string AttentionNotSet {
            get {
                return ResourceManager.GetString("AttentionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cfg.
        /// </summary>
        public static string cfg {
            get {
                return ResourceManager.GetString("cfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CfgFilename.
        /// </summary>
        public static string CfgFilename {
            get {
                return ResourceManager.GetString("CfgFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cfg Filename should be set to save setting..
        /// </summary>
        public static string CfgFilenameNotSet {
            get {
                return ResourceManager.GetString("CfgFilenameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration number cannot be blank..
        /// </summary>
        public static string ConfigurationTypeNotSet {
            get {
                return ResourceManager.GetString("ConfigurationTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Package.
        /// </summary>
        public static string CreatePackage {
            get {
                return ResourceManager.GetString("CreatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Caught.
        /// </summary>
        public static string ExceptionCaught {
            get {
                return ResourceManager.GetString("ExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Folder.
        /// </summary>
        public static string FirmFolder {
            get {
                return ResourceManager.GetString("FirmFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm location is required. Please provide firm folder path..
        /// </summary>
        public static string FirmFolderNotSet {
            get {
                return ResourceManager.GetString("FirmFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Settings.
        /// </summary>
        public static string FolderSetting {
            get {
                return ResourceManager.GetString("FolderSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location cannot be blank..
        /// </summary>
        public static string LocationNotSet {
            get {
                return ResourceManager.GetString("LocationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory cannot be blank..
        /// </summary>
        public static string OutputDirectoryNotSet {
            get {
                return ResourceManager.GetString("OutputDirectoryNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Tool is already running..
        /// </summary>
        public static string PackageAlreadyRunning {
            get {
                return ResourceManager.GetString("PackageAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Completed.
        /// </summary>
        public static string PackageCompleted {
            get {
                return ResourceManager.GetString("PackageCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package directory cannot be blank..
        /// </summary>
        public static string PackageDirectoryNotSet {
            get {
                return ResourceManager.GetString("PackageDirectoryNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackageTool.
        /// </summary>
        public static string PackageTool {
            get {
                return ResourceManager.GetString("PackageTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Instance cannot be blank..
        /// </summary>
        public static string PrinterInstanceNotSet {
            get {
                return ResourceManager.GetString("PrinterInstanceNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to proceed creating this package?.
        /// </summary>
        public static string ProceedCreatePackageQuestion {
            get {
                return ResourceManager.GetString("ProceedCreatePackageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name cannot be blank..
        /// </summary>
        public static string ProjectNameNotSet {
            get {
                return ResourceManager.GetString("ProjectNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project number cannot be blank..
        /// </summary>
        public static string ProjectNumberNotSet {
            get {
                return ResourceManager.GetString("ProjectNumberNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Templates.
        /// </summary>
        public static string ReportTemplates {
            get {
                return ResourceManager.GetString("ReportTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save new firm directory?.
        /// </summary>
        public static string SaveFirmDirectoryQuestion {
            get {
                return ResourceManager.GetString("SaveFirmDirectoryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatory cannot be blank..
        /// </summary>
        public static string SignatoryNotSet {
            get {
                return ResourceManager.GetString("SignatoryNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmittal number cannot be blank..
        /// </summary>
        public static string TransmittalNumberNotSet {
            get {
                return ResourceManager.GetString("TransmittalNumberNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSR.
        /// </summary>
        public static string XSR {
            get {
                return ResourceManager.GetString("XSR", resourceCulture);
            }
        }
    }
}
