// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmdDisplayExportDrawingsDialog", "", "main_frame");
            akit.TabChange("diaExportDrawings", "tabWndProperties", "tabOptions");
            akit.ValueChange("diaExportDrawings", "chkUsePaperSpace", "0");
            akit.TabChange("diaExportDrawings", "tabWndProperties", "tabExportFile");
            akit.ValueChange("diaExportDrawings", "optMnuFileType", "1");
            akit.ValueChange("diaExportDrawings", "textFileName", "");
            akit.PushButton("butExport", "diaExportDrawings");
            akit.PushButton("butCancel", "diaExportDrawings");
        }
    }
}
